---
- name: Configure VLAN interfaces and DHCP (only if not present)
  tags: vlan
  loop: "{{ vlans }}"
  loop_control:
    label: "VLAN {{ item.id }}"
  when: vlan_int + '.' + (item.id | string) not in vyos_facts_int
  vyos_config:
    lines:
      - set interfaces ethernet {{ vlan_int }} vif {{ item.id }} address {{ item.ip }}
      - set interfaces ethernet {{ vlan_int }} vif {{ item.id }} description {{ item.name }}
      - set service dhcp-server shared-network-name {{ item.name }} authoritative
      - set service dhcp-server shared-network-name {{ item.name }} subnet {{ item.network }} lease 86400
      - set service dhcp-server shared-network-name {{ item.name }} subnet {{ item.network }} option default-router {{ item.ip.split('/')[0] }}
      - set service dhcp-server shared-network-name {{ item.name }} subnet {{ item.network }} option name-server {{ item.ip.split('/')[0] }}
      - set service dhcp-server shared-network-name {{ item.name }} subnet {{ item.network }} range 0 start {{ item.dhcp_start }}
      - set service dhcp-server shared-network-name {{ item.name }} subnet {{ item.network }} range 0 stop {{ item.dhcp_end }}
      - set service dhcp-server shared-network-name {{ item.name }} subnet {{ item.network }} subnet-id {{ item.id }}
    save: true
