---
- name: Full VyOS configuration
  gather_facts: no
  hosts: vyos
  roles:
    - ip
    - static
    - vlan_dhcp

- name: Proxy configuration
  gather_facts: no
  hosts: proxy
  roles:
    - proxy

- name: OPNsense configuration
  gather_facts: no
  hosts: localhost
  module_defaults:
    group/ansibleguy.opnsense.all:
      firewall: '192.168.2.1'
      api_credential_file: '/home/ansible/.secret/opn.key'
    ansibleguy.opnsense.list:
      target: 'rule'
  roles:
    - opnsense
    - ids
